name: DEV CI/CD to S3 and CloudFront

on:
    push:
        branches:
            - develop

jobs:
    DEV_MY_CICD_JOBS:
        runs-on: ubuntu-latest
        steps:
            - name: 레포 다운 받기
              uses: actions/checkout@v5

            - name: 의존성 설치 -> 빌드
              run: |
                npm install
                npm run build
            
            - name: aws 권한 획득
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                aws-region: ap-northeast-2
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: s3 비우기
              run: aws s3 rm --recursive s3://dev-study-tracker

            - name: s3에 dist 채우기
              run: aws s3 cp ./dist s3://dev-study-tracker --recursive

            - name: cloudfront 캐시 무효화
              run: aws cloudfront create-invalidation --distribution-id E1XMUGJRMP58OX --path "/*"